name: CI
permissions:
  contents: read
  pull-requests: write
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Setup Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Check formatting
        run: npm run lint
      - name: Check types
        run: npm run typecheck
      - name: Build
        run: npm run build
      - id: check-unowned-dependencies
        name: Check unowned dependencies
        continue-on-error: true
        uses: ./
        with:
          dependency-file: 'package.json'
          loader: '@dependency-owners/package-json-loader'
      - name: Test action
        run: |
          if [[ "${{ steps.check-unowned-dependencies.outputs.unowned-dependencies }}" != "[]" ]]; then
            exit 1
          fi
          if [[ "${{ steps.check-unowned-dependencies.outputs.unowned-dependencies-found }}" == "true" ]]; then
            exit 1
          fi
      - name: Assign reviewers to dependency changes
        uses: dependency-owners/assign@ac1fd950a2356ec64fe9dc92f21cd51f05aba420 # v2.0.24
        with:
          dependency-file: 'package.json'
          loader: '@dependency-owners/package-json-loader'
      - name: Check dist for changes
        run: git diff --exit-code --quiet ./dist
